format = """
[╭─](bold cyan)\
$os\
$username\
[](fg:#a3aed2 bg:#769ff0)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#394260 bg:#212736)\
$package\
$nodejs\
$python\
$rust\
$golang\
$java\
$kotlin\
$lua\
$php\
$ruby\
$swift\
$terraform\
$docker_context\
$kubernetes\
[](fg:#212736 bg:#16161e)\
$aws\
$gcloud\
$azure\
[](fg:#16161e bg:#0f0f14)\
$cmd_duration\
$jobs\
$battery\
$time\
[](fg:#0f0f14)\
$line_break\
[╰─](bold cyan)$character"""

[os]
format = "[$symbol](bg:#a3aed2 fg:#090c0c)"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:#a3aed2 fg:#090c0c"
style_root = "bg:#a3aed2 fg:#ff6b6b"
format = '[ $user ]($style)'

[hostname]
ssh_only = false
style = "bg:#394260 fg:#769ff0"
format = '[ $hostname ]($style)'

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"
read_only = " 󰌾"
home_symbol = " ~"
fish_style_pwd_dir_length = 1

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Videos" = " "
"Desktop" = "󰇄 "
"Code" = " "
"src" = " "
"bin" = " "
".config" = " "
"node_modules" = " "
".git" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'
truncation_length = 20

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
conflicted = "🏳"
deleted = ""
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
modified = ""
renamed = "󰁕"
staged = ""
stashed = ""
untracked = ""

[git_metrics]
added_style = "fg:#769ff0 bg:#394260"
deleted_style = "fg:#769ff0 bg:#394260"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = "🐍"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = "🦀"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[java]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[kotlin]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[lua]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[ruby]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[swift]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[terraform]
symbol = "💠"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[docker_context]
symbol = ""
style = "bg:#16161e"
format = '[[ $symbol ($context) ](fg:#769ff0 bg:#16161e)]($style)'

[kubernetes]
symbol = "󱃾"
style = "bg:#16161e"
format = '[[ $symbol ($context) ](fg:#769ff0 bg:#16161e)]($style)'
disabled = false

[aws]
symbol = ""
style = "bg:#0f0f14"
format = '[[ $symbol ($profile) ](fg:#769ff0 bg:#0f0f14)]($style)'

[gcloud]
symbol = "󱇶"
style = "bg:#0f0f14"
format = '[[ $symbol ($project) ](fg:#769ff0 bg:#0f0f14)]($style)'

[azure]
symbol = "󰠅"
style = "bg:#0f0f14"
format = '[[ $symbol ($subscription) ](fg:#769ff0 bg:#0f0f14)]($style)'
disabled = false

[time]
disabled = false
time_format = "%R"
style = "bg:#0f0f14"
format = '[[  $time ](fg:#a0a9cb bg:#0f0f14)]($style)'

[cmd_duration]
min_time = 2_000
style = "bg:#0f0f14"
format = '[[ 󰔛 $duration ](fg:#a0a9cb bg:#0f0f14)]($style)'

[jobs]
symbol = ""
style = "bg:#0f0f14"
format = '[[ $symbol $number ](fg:#a0a9cb bg:#0f0f14)]($style)'

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
style = "bg:#0f0f14"
format = '[[ $symbol $percentage ](fg:#a0a9cb bg:#0f0f14)]($style)'

[[battery.display]]
threshold = 10
style = "bg:#ff6b6b"

[[battery.display]]
threshold = 30
style = "bg:#ffb86c"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold blue)"

[package]
symbol = "󰏗"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
disabled = false
